name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Config.js with Secrets
        run: |
          mkdir -p src/api
          echo "const MOVIE_API_KEY = '${{ secrets.MOVIE_API_KEY }}';" > src/api/config.js
          echo "const NEWS_API_KEY = '${{ secrets.NEWS_API_KEY }}';" >> src/api/config.js
          echo "export { MOVIE_API_KEY, NEWS_API_KEY };" >> src/api/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./